// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { application } from '../libs/stimulus'

import RubricsCalculatorController from './rubrics_calculator_controller'
application.register('rubrics-calculator', RubricsCalculatorController)