// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { application as app } from '../libs/stimulus'
import RubricsCalculatorController from './rubrics_calculator_controller'
import TransfereeCurriculumController from './transferee_curriculum_controller'

app.register('rubrics-calculator', RubricsCalculatorController)
app.register('transferee-curriculum', TransfereeCurriculumController)
